set -g mouse on
set -g history-limit 50000

set -g status-style "bg=#1A1614,fg=#E2D8D0"
set -g status-left-style "bg=#1A1614,fg=#E2D8D0"
set -g status-right-style "bg=#1A1614,fg=#E2D8D0"
set -g window-status-style "bg=#1A1614,fg=#E2D8D0"
set -g window-status-current-style "bg=#1A1614,fg=#E2D8D0,bold"
