# --- Environment ---
env FZF_DEFAULT_OPTS=--bind alt-w:up,alt-s:down,alt-a:backward-char,alt-d:forward-char,alt-space:accept --gutter=' ' --scrollbar='█' --color=bg:-1,gutter:-1,border:#693638,separator:#D6AA7E,preview-border:#D6AA7E,hl:#D4B820,hl+:#D4B820,pointer:#D4B820,marker:#D4B820,bg+:#000000,prompt:#D4B820,info:#D6AA7E,header:#D6AA7E,scrollbar:#D4B820

# --- Behavior ---
confirm_os_window_close 0

# --- Appearance ---
hide_window_decorations yes
tab_bar_style hidden
window_padding_width 10
background_opacity 0.9
dynamic_background_opacity yes

# --- Font ---
font_size        12.0
font_family      family="JetBrainsMono Nerd Font" style="SemiBold"
bold_font        auto
italic_font      auto
bold_italic_font auto

# --- Noctalia Colors ---
# background            #693638
background            #693638
foreground            #F0B6B6
cursor                #1AAAD4
cursor_text_color     #F0B6B6
selection_background  #1AAAD4
selection_foreground  #F0B6B6

color0  #F0B6B6
color1  #D4B820
color2  #A1C4B4
color3  #ED2658
color4  #1AAAD4
# color5  #B1B9F9  #F0B6B6
color5  #ED6D42
color6  #1AAAD4
color7  #D6AA7E
color8  #716E75
color9  #D4B820
color10 #A1C4B4
color11 #ED2658
color12 #1AAAD4
# color13 #B1B9F9  #F0B6B6
color13 #ED6D42
color14 #1AAAD4
color15 #D6AA7E

# --- Kitty no-ops (pass through to Yazi) ---
map ctrl+c no_op
map ctrl+v no_op
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+p no_op
map ctrl+shift+x no_op
map ctrl+x no_op
map ctrl+g no_op
map ctrl+f no_op
map ctrl+s no_op
map ctrl+n no_op
map ctrl+t no_op
map ctrl+r no_op
map ctrl+e no_op
map ctrl+period no_op
map ctrl+h no_op
map ctrl+j no_op
map ctrl+i no_op
map ctrl+delete no_op
map ctrl+shift+delete no_op
map ctrl+shift+q no_op
map ctrl+p no_op
map ctrl+o no_op
map alt+1 no_op
map alt+2 no_op
map alt+3 no_op
map alt+4 no_op
map alt+5 no_op
map alt+6 no_op
map alt+7 no_op
map alt+8 no_op
map alt+9 no_op

# --- Pass-through keybinds (for Yazi input fields) ---
map ctrl+w send_text all \x7f
map alt+space no_op
map alt+q no_op
map alt+e no_op
