# --- Environment ---
env FZF_DEFAULT_OPTS=--bind alt-w:up,alt-s:down,alt-a:backward-char,alt-d:forward-char

# --- Behavior ---
confirm_os_window_close 0

# --- Appearance ---
hide_window_decorations yes
tab_bar_style hidden
window_padding_width 10
background_opacity 0.9
dynamic_background_opacity yes

# --- Font ---
font_size        12.0
font_family      family="JetBrainsMono Nerd Font" style="Bold"
bold_font        auto
italic_font      auto
bold_italic_font auto

# --- Noctalia Colors ---
# background            #914059
background            #7A2E2E
foreground            #FFFFFF
cursor                #00B6C2
cursor_text_color     #FFFFFF
selection_background  #00B6C2
selection_foreground  #FFFFFF

color0  #FFFFFF
color1  #FFA726
color2  #17C182
color3  #D0A7AF
color4  #00B6C2
# color5  #B1B9F9  #FFFFFF
color5  #FF6EB4
color6  #00B6C2
color7  #D0A7AF
color8  #9E9080
color9  #FFA726
color10 #17C182
color11 #D0A7AF
color12 #00B6C2
# color13 #B1B9F9  #FFFFFF
color13 #FF6EB4
color14 #00B6C2
color15 #D0A7AF

# --- Kitty no-ops (pass through to Yazi) ---
map ctrl+shift+c no_op
map ctrl+shift+p no_op
map ctrl+shift+x no_op
map ctrl+x no_op
map ctrl+g no_op
map ctrl+f no_op
map ctrl+s no_op
map ctrl+n no_op
map ctrl+t no_op
map ctrl+r no_op
map ctrl+e no_op
map ctrl+period no_op
map ctrl+h no_op
map ctrl+j no_op
map ctrl+i no_op
map ctrl+delete no_op
map ctrl+shift+delete no_op
map ctrl+shift+q no_op
map ctrl+p no_op
map ctrl+o no_op
map alt+1 no_op
map alt+2 no_op
map alt+3 no_op
map alt+4 no_op
map alt+5 no_op
map alt+6 no_op
map alt+7 no_op
map alt+8 no_op
map alt+9 no_op

# --- Pass-through keybinds (for Yazi input fields) ---
map ctrl+w send_text all \x7f
map alt+q no_op
map alt+e no_op
