# --- Environment ---
env FZF_DEFAULT_OPTS=--bind alt-w:up,alt-s:down,alt-a:backward-char,alt-d:forward-char,alt-space:accept --gutter=' ' --scrollbar='█' --color=bg:-1,gutter:-1,border:#6E3840,separator:#DA9E8A,preview-border:#DA9E8A,hl:#ED6D42,hl+:#ED6D42,pointer:#ED6D42,marker:#ED6D42,bg+:#000000,prompt:#ED6D42,info:#DA9E8A,header:#DA9E8A,scrollbar:#ED6D42

# --- Behavior ---
confirm_os_window_close 0

# --- Appearance ---
hide_window_decorations yes
tab_bar_style hidden
window_padding_width 10
background_opacity 0.9
dynamic_background_opacity yes

# --- Font ---
font_size        12.0
font_family      family="JetBrainsMono Nerd Font" style="SemiBold"
bold_font        auto
italic_font      auto
bold_italic_font auto

# --- Noctalia Colors ---
# background            #6E3840
background            #6E3840
foreground            #E2D8D0
cursor                #1AAAD4
cursor_text_color     #E2D8D0
selection_background  #1AAAD4
selection_foreground  #E2D8D0

color0  #E2D8D0
color1  #ED6D42
color2  #96E050
color3  #ED2658
color4  #1AAAD4
# color5  #B1B9F9  #E2D8D0
color5  #ED6D42
color6  #1AAAD4
color7  #DA9E8A
color8  #716E75
color9  #ED6D42
color10 #96E050
color11 #ED2658
color12 #1AAAD4
# color13 #B1B9F9  #E2D8D0
color13 #ED6D42
color14 #1AAAD4
color15 #DA9E8A

# --- Kitty no-ops (pass through to Yazi) ---
map ctrl+c no_op
map ctrl+v no_op
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+p no_op
map ctrl+shift+x no_op
map ctrl+x no_op
map ctrl+g no_op
map ctrl+f no_op
map ctrl+s no_op
map ctrl+n no_op
map ctrl+t no_op
map ctrl+r no_op
map ctrl+e no_op
map ctrl+period no_op
map ctrl+h no_op
map ctrl+j no_op
map ctrl+i no_op
map ctrl+delete no_op
map ctrl+shift+delete no_op
map ctrl+shift+q no_op
map ctrl+p no_op
map ctrl+o no_op
map alt+1 no_op
map alt+2 no_op
map alt+3 no_op
map alt+4 no_op
map alt+5 no_op
map alt+6 no_op
map alt+7 no_op
map alt+8 no_op
map alt+9 no_op

# --- Pass-through keybinds (for Yazi input fields) ---
map ctrl+w send_text all \x7f
map alt+space no_op
map alt+q no_op
map alt+e no_op
