include kitty.conf

# Restore keybinds that are no_op'd for yazi but needed in launcher/fsel
map ctrl+n send_text all \x0e
map ctrl+p send_text all \x10
map ctrl+q send_text all \x11
map ctrl+h send_text all \x08
map ctrl+j send_text all \x0a
map ctrl+i send_text all \x09
map alt+q send_text all \x1bq
map alt+e send_text all \x1be
map alt+w send_text all \x1b[A
map alt+s send_text all \x1b[B
