music_directory    "~/Music/Music_Linux/mp3 library/Music"
db_file            "~/.local/share/mpd/database"
log_file           "~/.local/share/mpd/log"
pid_file           "~/.local/share/mpd/pid"
state_file         "~/.local/share/mpd/state"
playlist_directory "~/.local/share/mpd/playlists"

audio_output {
    type  "pipewire"
    name  "PipeWire"
}
