# General
background = "#693638"
border_fg = "#c99e76"
text_fg = "#F0B6B6"
dimmed_text_fg = "#716E75"

# Input
input_text_fg = "#D4B820"
result_count_fg = "#D4B820"

# Results
result_name_fg = "#F0B6B6"
result_line_number_fg = "#c99e76"
result_value_fg = "#F0B6B6"
selection_fg = "#F0B6B6"
selection_bg = "#000000"
match_fg = "#D4B820"

# Preview
preview_title_fg = "#c99e76"

# Modes
channel_mode_fg = "#693638"
channel_mode_bg = "#D4B820"
remote_control_mode_fg = "#693638"
remote_control_mode_bg = "#ED6D42"
send_to_channel_mode_fg = "#ED6D42"
