# General
background = "#6E3840"
border_fg = "#DA9E8A"
text_fg = "#E2D8D0"
dimmed_text_fg = "#716E75"

# Input
input_text_fg = "#ED6D42"
result_count_fg = "#ED6D42"

# Results
result_name_fg = "#E2D8D0"
result_line_number_fg = "#DA9E8A"
result_value_fg = "#E2D8D0"
selection_fg = "#E2D8D0"
selection_bg = "#000000"
match_fg = "#ED6D42"

# Preview
preview_title_fg = "#DA9E8A"

# Modes
channel_mode_fg = "#6E3840"
channel_mode_bg = "#ED6D42"
remote_control_mode_fg = "#6E3840"
remote_control_mode_bg = "#ED6D42"
send_to_channel_mode_fg = "#ED6D42"
