[metadata]
name = "Clipboard"
description = "Clipboard manager"

[ui]
orientation = "portrait"

[ui.preview_panel]
size = 70
scrollbar = true
word_wrap = true
border_type = "thick"
hidden = false

[source]
command = "cclip list"
display = "{split:\t:2}"

[preview]
command = "cclip get '{split:\t:0}'"

[keybindings]
enter = "actions:copy"
alt-space = "actions:copy"
ctrl-c = "actions:copy"

[actions.copy]
description = "Copy to clipboard"
command = "cclip copy '{split:\t:0}'"
mode = "execute"
