[metadata]
name = "Files"
description = "Browse and open files"

[source]
command = "fd -H -t f . /var/home/samuel/ | awk '{ gsub(\"/var/home/samuel/\", \"~/\"); match($0, /.*\\//); dir = substr($0, 1, RLENGTH); file = substr($0, RLENGTH+1); printf \"\\033[36m%s\\033[0m%s\\n\", dir, file }'"
ansi = true
output = "{strip_ansi}"

[ui]
orientation = "landscape"

[ui.preview_panel]
# Preview panel size (percentage of screen width/height)
size = 50
#header = ""
#footer = ""
scrollbar = true
word_wrap = true
border_type = "thick"
# padding = { left = 0, right = 0, top = 0, bottom = 0 }
hidden = false

[preview]
command = "bash -c 'p=$(sed \"s|^~/|/var/home/samuel/|\" <<< \"$1\"); bat --color=always --style=plain --theme=Noctalia \"$p\"' -- '{strip_ansi}'"

[keybindings]
enter = "actions:open"
alt-space = "actions:open"
ctrl-c = "actions:copy"

[actions.open]
description = "Open with VSCode"
command = "bash -c 'for f in \"$@\"; do p=$(sed \"s|^~/|/var/home/samuel/|\" <<< \"$f\"); code --reuse-window \"$p\"; done' -- {split:\\n:..|map:{strip_ansi|append:'|prepend:'}|join: }"
mode = "execute"
separator = "\n"

[actions.copy]
description = "Copy to clipboard (full path)"
command = "printf '%s' \"{strip_ansi}\" | sed 's|^~/|/var/home/samuel/|' | wl-copy"
mode = "fork"
